remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: true
  executive: true

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: true
  volunteer: false

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Software engineer
  - Software Developer
  - DevOps Engineer
  - Frontend Developer
  - Backend Developer
  - Full Stack Developer
  - Mobile App Developer
  - Embedded Systems Engineer
  - Cloud Engineer
  - Technical Program Manager
  - Product Manager
  - Business Analyst (IT/Software)
  - Software Sales Engineer
  - Customer Success Manager (SaaS)
  - IT Project Manager
  - Solutions Architect
  - Technical Consultant
  - Enterprise Architect
  - Technical Product Manager
  - UX/UI Designer
  - Data Scientist
  - IT Business Partner
  - Chief Technology Officer (CTO)

locations:
  - Germany
  - France
  - Spain
  - Portugal
  - United States
  - Canada

apply_once_at_company: true

distance: 100

company_blacklist:
  - Alten

title_blacklist:

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
